---
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/build
  build-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - build
      - omnilint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/build
      - run: rm -f .gitignore
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          branch: gh-pages
          folder: .
          single-commit: true
          clean: true
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: docker://lpenz/omnilint:0.5.2
